src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
class Client
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date = null;


    private ?Fournisseur $Fournisseur = null;

    /**
     * @var Collection<int, CommandeProduit>
     */
    #[ORM\OneToMany(targetEntity: CommandeProduit::class, mappedBy: 'commande')]
    private Collection $commande;



    public function __construct()
    {
        $this->date = new \DateTime();
        $this->commande = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getFournisseur(): ?Fournisseur
    {
        return $this->Fournisseur;
    }

    public function setFournisseur(?Fournisseur $Fournisseur): static
    {
        $this->Fournisseur = $Fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, CommandeProduit>
     */
    public function getCommande(): Collection
    {
        return $this->commande;
    }

    public function addCommande(CommandeProduit $commande): static
    {
        if (!$this->commande->contains($commande)) {
            $this->commande->add($commande);
            $commande->setCommande($this);
        }

        return $this;
    }

    public function removeCommande(CommandeProduit $commande): static
    {
        if ($this->commande->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getCommande() === $this) {
                $commande->setCommande(null);
            }
        }

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $reference = null;

    #[ORM\Column(length: 255)]
    private ?string $designation = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $lot = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $peremption = null;

    #[ORM\Column(nullable: true)]
    private ?int $prixpublic = null;

    #[ORM\Column]
    private ?int $stock = null;
//
//    #[ORM\Column(type: Types::DATE_MUTABLE)]
//    private ?\DateTimeInterface $creation = null;

    #[ORM\Column]
    private ?bool $tva = null;

    /**
     * @var Collection<int, Fournisseur>
     */
    #[ORM\ManyToMany(targetEntity: Fournisseur::class, inversedBy: 'produits')]
    private Collection $Fournisseur;

    /**
     * @var Collection<int, Commande>
     */
    #[ORM\ManyToMany(targetEntity: Commande::class, mappedBy: 'Produits')]
    private Collection $commandes;

    /**
     * @var Collection<int, CommandeProduit>
     */
    #[ORM\OneToMany(targetEntity: CommandeProduit::class, mappedBy: 'Produit')]
    private Collection $produit;

    /**
     * @var Collection<int, VenteProduit>
     */
    #[ORM\OneToMany(targetEntity: VenteProduit::class, mappedBy: 'produit')]
    private Collection $venteProduits;

    public function __construct()
    {
        $this->stock = 0;
        $this->tva = false;
        $this->Fournisseur = new ArrayCollection();
        $this->detailcommandes = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->produit = new ArrayCollection();
        $this->venteProduits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): static
    {
        $this->designation = $designation;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getLot(): ?int
    {
        return $this->lot;
    }

    public function setLot(int $lot): static
    {
        $this->lot = $lot;

        return $this;
    }

    public function getPeremption(): ?\DateTimeInterface
    {
        return $this->peremption;
    }

    public function setPeremption(\DateTimeInterface $peremption): static
    {
        $this->peremption = $peremption;

        return $this;
    }

    public function getPrixpublic(): ?int
    {
        return $this->prixpublic;
    }

    public function setPrixpublic(int $prixpublic): static
    {
        $this->prixpublic = $prixpublic;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

//    public function getCreation(): ?\DateTimeInterface
//    {
//        return $this->creation;
//    }
//
//    public function setCreation(\DateTimeInterface $creation): static
//    {
//        $this->creation = $creation;
//
//        return $this;
//    }


    public function isTva(): ?bool
    {
        return $this->tva;
    }

    public function setTva(bool $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    /**
     * @return Collection<int, Fournisseur>
     */
    public function getFournisseur(): Collection
    {
        return $this->Fournisseur;
    }

    public function addFournisseur(Fournisseur $fournisseur): static
    {
        if (!$this->Fournisseur->contains($fournisseur)) {
            $this->Fournisseur->add($fournisseur);
        }

        return $this;
    }

    public function removeFournisseur(Fournisseur $fournisseur): static
    {
        $this->Fournisseur->removeElement($fournisseur);

        return $this;
    }


    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->addProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            $commande->removeProduit($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, CommandeProduit>
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(CommandeProduit $produit): static
    {
        if (!$this->produit->contains($produit)) {
            $this->produit->add($produit);
            $produit->setProduit($this);
        }

        return $this;
    }

    public function removeProduit(CommandeProduit $produit): static
    {
        if ($this->produit->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProduit() === $this) {
                $produit->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, VenteProduit>
     */
    public function getVenteProduits(): Collection
    {
        return $this->venteProduits;
    }

    public function addVenteProduit(VenteProduit $venteProduit): static
    {
        if (!$this->venteProduits->contains($venteProduit)) {
            $this->venteProduits->add($venteProduit);
            $venteProduit->setProduit($this);
        }

        return $this;
    }

    public function removeVenteProduit(VenteProduit $venteProduit): static
    {
        if ($this->venteProduits->removeElement($venteProduit)) {
            // set the owning side to null (unless already changed)
            if ($venteProduit->getProduit() === $this) {
                $venteProduit->setProduit(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use App\Entity\Fournisseur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('reference')
            ->add('designation')
            ->add('prix')
            ->add('description')

//            ->add('quantite')
//            ->add('lot')
//            ->add('peremption', null, [
//                'widget' => 'single_text',
//            ])
//            ->add('prixpublic')
//            ->add('stock')
//            ->add('creation', null, [
//                'widget' => 'single_text',
//            ])
//            ->add('mincommande')
            ->add('tva')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('{{ 'Voulez-vous supprimer le produit?'|trans }}');"  style="display: inline;">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger"><i class="fa fa-trash"></i></button>
</form>

templates/produit/_form.html.twig
{{ form_start(form, {'attr' : { 'id' : 'form'}}) }}

<div class="col-lg-8 offset-lg-2 mt-4 fond pb-4 pt-3 px-5">
    <h4 class="mb-3 p-2">
        <i class="fa-brands fa-product-hunt mr-2"></i>
        {{ 'Nouveau Produit'|trans }}
    </h4>
    <hr class=" mb-5">
    <div class="row">
        <div class="col-md-6 mb-4">
            {{ form_row(form.reference, {'attr':{'placeholder':'Code produit *'}, 'label':false}) }}
        </div>
        <div class="col-md-6 mb-4">
            {{ form_row(form.designation, {'attr':{'placeholder':'Désignation *'}, 'label':false}) }}
        </div>
        <div class="col-md-6 mb-4">
            {{ form_row(form.telephone, {'attr':{'placeholder':'Téléphone *'}, 'label':false}) }}
        </div>
        <div class="col-md-6 mb-4">
            {{ form_row(form.prix, {'attr':{'placeholder':'Prix *'}, 'label':false}) }}
        </div>
        <div class="col-md-6 mb-4">
            {{ form_row(form.fabricant, {'attr':{'placeholder':'Fabriquant *'}, 'label':false}) }}
        </div>
        <div class="col-md-6 mb-4">
            {{ form_row(form.description, {'attr':{'placeholder':'description *'}, 'label':false}) }}
        </div>
        <div class="col-md-12 mb-4">
            {{ form_row(form.adresse, {'attr':{'placeholder':'Adresse *'}, 'label':false}) }}
        </div>
        <div class="col-md-4 mb-4">
            {{ form_row(form.tva, {'label':'Soumis à la TVA'}) }}
        </div>
        {{ form_rest(form) }}
    </div>
    <div class="col-md-4 pt-3 fond-btn">
        <div class="text-center">
            {#                <div class="row">#}
            <button type="button" class="btn btn-shadow btn-success btn-normal mb-3 mr-3" id="send" onclick="load_btn('send')">
                <i class="fa fa-save"></i>
                {{ 'Enregistrer'|trans }}
            </button>

            <button type="reset" class="btn btn-shadow btn-danger btn-normal mb-3">
                <i class="fa fa-delete-left"></i>
                {{ 'Effacer'|trans }}
            </button>
        </div>
        {{ form_end(form) }}
    </div>
</div>

templates/produit/edit.html.twig
{% extends 'layout.html.twig' %}

{% block body %}
    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/produit/index.html.twig
{% extends 'layout.html.twig' %}
{% block produit %}active{% endblock %}
{% block body %}

    <div class="container-fluid mt-3 fond">
        <div class="row">
            <div class="col-md-6">
                <h3 class="mb-3 text-bold">
                    <i class="fa-brands fa-product-hunt mr-2"></i>
                    {{ "Liste des Produits"|trans }}
                </h3>
            </div>
            <div class="col-md-6">
                <a href="{{ path('app_produit_new') }}" class="btn btn-primary float-end"><i class="fa fa-plus"></i> Nouveau produit</a>
            </div>
        </div>
        <hr>

        <table id="liste" class="table table-success-light table-bordered table-hover table-striped text-center">
            <thead>
            <tr>
                <th>{{ 'Code'|trans }}</th>
                <th class="text-start">{{ 'Designation'|trans }}</th>
                <th>{{ 'Prix'|trans }}</th>
                <th>{{ 'Description'|trans }}</th>
                <th>{{ 'Tva'|trans }}</th>
                <th>{{ 'Actions'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for produit in produits %}
                <tr>
                    <td>{{ produit.reference }}</td>
                    <td class="text-start">{{ produit.designation }}</td>
{#                    <td class="text-start">{{ produit.fournisseur[0].adressez }}</td>#}
                    <td>{{ produit.prix }}</td>
                    <td>{{ produit.description }}</td>
                    <td>{{ produit.tva ? 'Yes' : 'No' }}</td>
                    <td class="text-nowrap">
                        <a class="btn btn-success" title="{{ 'Voir'|trans }}" href="{{ path('app_produit_show', {'id': produit.id}) }}">
                            <i class="fa fa-eye"></i>
                        </a>
                        <a class="btn btn-primary" title="{{ 'Modifier'|trans }}" href="{{ path('app_produit_edit', {'id': produit.id}) }}">
                            <i class="fa fa-edit"></i>
                        </a>
                        {{ include('produit/_delete_form.html.twig') }}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="17">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/produit/new.html.twig
{% extends 'layout.html.twig' %}

{% block body %}


    {{ include('produit/_form.html.twig') }}


    {{ form_end(form) }}

{% endblock %}

templates/produit/show.html.twig
{% extends 'layout.html.twig' %}
{% block body %}
    <div class="col-lg-10 offset-lg-2 mt-4 fond pb-4 pt-3 px-5">
        <h4 class="mb-3 p-2">
            <i class="fa-brands fa-product-hunt mr-2"></i>
            {{ "Détails Produit"|trans }}
        </h4>
        <hr class=" mb-5">
    <table class="table table-success-light table-bordered table-hover table-striped w-100">
        <tbody>
            <tr>
                <th>Reference</th>
                <td>{{ produit.reference }}</td>
            </tr>
            <tr>
                <th>Designation</th>
                <td>{{ produit.designation }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit.prix }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ produit.description }}</td>
            </tr>
{#            <tr>#}
{#                <th>Quantité</th>#}
{#                <td>{{ produit.quantite }}</td>#}
{#            </tr>#}
            <tr>
                <th>Tva</th>
                <td>{{ produit.tva ? 'Yes' : 'No' }}</td>
            </tr>
            {% for fournis in produit.fournisseur %}
                <tr>
                    <th>Nom fournisseur</th>
                    <td>{{ fournis.nom }}</td>
                </tr>
                <tr>
                    <th>Telephone fournisseur</th>
                    <td>{{ fournis.telephone }}</td>
                </tr>
                <tr>
                    <th>Email fournisseur</th>
                    <td>{{ fournis.email }}</td>
                </tr>
                <tr>
                    <th>Adresse fournisseur</th>
                    <td>{{ fournis.adresse }}</td>
                </tr>
                <tr>
                    <th>Pays fournisseur</th>
                    <td>{{ fournis.pays }}</td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="2">Aucun fournisseur</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

        <div class="col-md-3 offset-md-3 pt-3 fond-btn">
            <div class="text-center">
                <a href="{{ path('app_produit_index') }}" class="btn btn-shadow btn-success mb-3">Retour</a>
            </div>
        </div>
</div>

{% endblock %}